# -*- coding: utf-8 -*-
"""
Created on Mon Aug 24 14:12:28 2020

@author: chang
"""

# Title
title = "Nutrition App"
print(title)

# List of food categories
category =["Fruit", "Diary", "Vegetable", "Meat", "Fish"]

# Add items to category, append() takes exactly one argument
category.append("Egg")
category.append("Fat-Oil")
category.append("Beverage")

print(category)


# List of food - an empty list
food_list =[]

# Declare a food_item as dictionary with keys: "name", "category" and "nutrition_panel"
# The nutrition_panel is delcared as a dictionary with "Energy", "Fat", "Protein", etc.
food ={
    'name': "whole_egg" ,
    'category': "Egg",
    'nutrition_panel':{
        'Energy(kcal)': 118,
        'Fat(g)': 8.1,
        'Carbonhydrate(g)': 0.3,        
        'Protein(g)': 11.1 ,
        'Salt(mg)': 247.6,}          
    }

food_list.append(food)

food ={
    'name': "apple" ,
    'category': "Fruits",
    'nutrition_panel':{
        'Energy(kcal)': 37,
        'Fat(g)': 0.1,
        'Carbonhydrate(g)': 7.7,        
        'Protein(g)': 0.2 }          
    }

food_list.append(food)


print(food_list)

# Loop through food_list, print out name and nutrition info
for food in food_list:
    print(food['name'] + ":")
    print(food['nutrition_panel'])

# Loop through food_list, print out key and value pairs generated by dict.items()
for food in food_list:
    for pair in food.items():
       print(pair)

